### ISSUE TITLE
Updating a task in place

### ISSUE THREAD

**Issue by sholladay** [SamVerschueren/listr#1]
I am stoked about this module. I think it has potential to be _the_ way to represent any non-trivial CLI behavior. I can imagine it being used in Yeoman, test runners, etc.

One thing I think we will need is to address some of what @jamestalmage says in https://github.com/sindresorhus/np/issues/30#issuecomment-225275715.

> when I'm installing something that has a long build step as part of it's install ... I want to see what's causing the hold up

That is to say, tasks have an associated status that is meaningful in some cases. For npm, a progress bar may be useful, but even just seeing which dependency is currently being installed would help explain long installs at a quick glance.

To achieve this, I imagine a method that would allow me to update the task description in place. Or maybe just characters to the right of the task description if you want to be opinionated about it and protect end users from crazy mutations to the task list.

**Comment by jamestalmage** [comment]
One way to do this would be to allow tasks to return an Observable for a stream of strings.

Then show each string as it arrives (erasing the last string).

@SamVerschueren - If you look at the `write` method in AVA's mini-reporter. You can see how we combine stdout from the child process with the continually refreshed test status. It took quite a bit of trial and error to get it working across a wide variety of terminal emulators (if you see me using odd control character sequences in there, there is probably a reason), so I think it would be helpful to start there.

**Comment by SamVerschueren** [comment]
@jamestalmage Do you think the user of the module should implement that behaviour like using `log-update` to show the last returned value from the observable? Or should `listr` accept an option to show the last line of the output of the current task?

The first option offers the most flexibility for the user, but he needs to implement some things themselves.

**Comment by sindresorhus** [comment]
I prefer `listr` handle this.

**Comment by jamestalmage** [comment]
Log update probably won't work anyway. You need to track the cursor state in a way that log update won't allow

**Comment by SamVerschueren** [comment]
Does anyone of you guys know of a way I could intercept output from a task?

The easiest way for me would be that a task returns an observable which emits the output. But to be honest, that is not something I prefer. It makes implementing a task more difficult. But I'm not sure if it's possible to intercept the output...

**Comment by jamestalmage** [comment]
Use Observables. They are purpose built for what you want to accomplish.

You can recommend stream-to-observable.

Also, there is ongoing work in execa to allow observable output as well.

you could maybe use `stream-to-observable` and let them return streams.

**Comment by SamVerschueren** [comment]
> Also, there is ongoing work in execa to allow observable output as well.

Would be awesome! If I could help you out with implementing that, give a shout.

Implementing it now with Observables and it works nice. Hope to release it soon.

**Comment by SamVerschueren** [comment]
:tada:

<img src="https://raw.githubusercontent.com/SamVerschueren/listr/master/media/screenshot.gif">

**Comment by sindresorhus** [comment]
🎉🎉🎉🎉
