### ISSUE TITLE
Option to only show subtasks on failure

### ISSUE THREAD

**Issue by sindresorhus** [SamVerschueren/listr#10]
In `np` we have a `Git` task with some subtasks. Those subtasks finish quickly so the whole thing feels very jumpy. It would be nice if we could just not show them at all, but show in case of a failure.

**Comment by SamVerschueren** [comment]
Good idea!

**Comment by SamVerschueren** [comment]
Looking into implementing this. Shouldn't be that hard. Did you have an option name in mind?

I was thinking something like this:

```js
const tasks = new Listr(taskList);
```

Or if you want to hide the subtasks

```js
const tasks = new Listr({subtask: false}, taskList);
```

While typing this, I came up with another approach. It's more pageres like which might be cleaner.

```js
const tasks = new Listr(taskList)
    .renderSubtasks(false)
    .run();
```

// @jamestalmage

**Comment by sindresorhus** [comment]
I would go with:

```
const tasks = new Listr(taskList, {showSubtasks: false});
```

(Options at the end).

I don't like the Pageres approach. Would not have done that again.

**Comment by SamVerschueren** [comment]
Thanks!

![subtasks](https://cloud.githubusercontent.com/assets/1913805/16985353/1302f066-4e80-11e6-82ed-73c78798c828.gif)
