### ISSUE TITLE
Maybe provide some fallback if not on a TTY

### ISSUE THREAD

**Issue by andywer** [SamVerschueren/listr#11]
Hey!

For https://github.com/andywer/npm-launch I was thinking about a plain-text fallback in case `!require('tty').isatty(process.stdout)`. Right now you get all those control characters in the output when piping to a file or similar. In my particular case I have Jenkins/Travis builds in mind.

But maybe you are interested to solve that edge case directly in Listr?

<img width="566" alt="bildschirmfoto 2016-07-14 um 00 29 48" src="https://cloud.githubusercontent.com/assets/1842462/16822026/1fafc3fa-495a-11e6-9502-38e13c0bad98.png">

**Comment by jokeyrhyme** [comment]
Without a tty, colors and backtracking / replacing existing output is impossible. So perhaps the output just needs to drop all animations and colors?

Perhaps:
- only output the tasks one by one, not all in advance
- for each task, output its text, and an ellipsis, and then "done" or an ASCII smiley or something when it's finished

E.g.

```
npmList ...
```

```
npmList ... done
runStandardLinter ...
```

```
npmList ... done
runStandardLinter ... done
wasteSomeTime ...
```

```
npmList ... done
runStandardLinter ... done
wasteSomeTime ... done
```

**Comment by jamestalmage** [comment]
Or just go verbose.

```
START <TASK_NAME>
task output
task output
task output
END <TASK_NAME>
```

If I am hunting down a problem in a Jenkins / Travis build, missing log data I suspect might be relevant is going to be a lot more frustrating than it is locally, where it is easy to rerun.

**Comment by andywer** [comment]
I guess ideally you could trigger "plain text output without control chars" and "verbose output" independently.

So it might be
```
START <task>
END <task>
```

or (if verbose)

```
START <task>
task output
END <task>
```

**Comment by andywer** [comment]
PS: But yes, verbose mode alone would also work for me right now 😉

**Comment by sveisvei** [comment]
Should be possible to activate with `CI=true` or/and `LISTR_OUTPUT=simple` or something along these lines.

**Comment by andywer** [comment]
listr-verbose-renderer almost does the job.

Just need a way to show all output if necessary (SamVerschueren/listr-verbose-renderer#1) and implement auto-switching to verbose renderer when in a CI scenario, piping to a file or similar.

**Comment by SamVerschueren** [comment]
Moving the discusion to #33. PR was added to add this.
