### ISSUE TITLE
A way to force verbose output.

### ISSUE THREAD

**Issue by jamestalmage** [SamVerschueren/listr#12]
See https://github.com/SamVerschueren/listr/issues/11#issuecomment-232545961

It would be good to have a way to access all the log data `listr` hides.

Maybe an environment variable?

**Comment by SamVerschueren** [comment]
I agree 👍

**Comment by SamVerschueren** [comment]
You can now make use of the [renderer](https://github.com/SamVerschueren/listr#renderer) option and set it to `verbose`. It will use the [listr-verbose-renderer](https://github.com/SamVerschueren/listr-verbose-renderer). If it doesn't fit your needs entirely or you want a cleaner/nicer output. Feel free to make suggestions in the repo or do a PR :).
