### ISSUE TITLE
Change colors?

### ISSUE THREAD

**Issue by GantMan** [SamVerschueren/listr#129]
This might seem pedantic but my error print is hard to read for my 2 preferred terminal themes.  This is rarely an issue outside of this tool.

Dark theme 1
![image](https://user-images.githubusercontent.com/997157/50648895-0a811280-0f42-11e9-9057-09b64641f262.png)

Dark theme 2
![image](https://user-images.githubusercontent.com/997157/50648922-1967c500-0f42-11e9-95be-f7eb0c2788b0.png)

See how hard it is to find/read it?

Rather than change my theme, I'd like to error on the side of caution and make errors red for everyone, like the ❌

**Comment by aj-may** [comment]
I see your point, but I think that might be more of an issue with your theme...

Mine seems to render nicely.  I'd be interested to see a wider sample.

<img width="333" alt="image" src="https://user-images.githubusercontent.com/1403235/59168669-b12a9a00-8b04-11e9-9519-16d85e228175.png">
