### ISSUE TITLE
Weird output

### ISSUE THREAD

**Issue by YurySolovyov** [SamVerschueren/listr#13]
running
```js
const Listr = require('listr');

const tasks = new Listr([
  {
    title: 'Task1',
    task: function() {
      return new Promise(function(resolve) {
        setTimeout(resolve, 1000);
      });
    }
  },
  {
    title: 'Task Two',
    task: function() {
      return new Promise(function(resolve) {
        setTimeout(resolve, 700);
      });
    }
  },
  {
    title: 'Task Next',
    task: function() {
      return new Promise(function(resolve) {
        setTimeout(resolve, 700);
      }).then(function() {
        return new Promise(function(resolve) {
          console.log('running ...');
          setTimeout(resolve, 700);
        });
      });
    }
  }
]);

tasks.run();
```

outputs:
```
node index

 ✔ Task1
 ✔ Task1
 ✔ Task Two
 ✔ Task Next
```

even though Task1 is set only once. Also, `running ...` does not gets printed at all

EDIT:
```
$ node -v
v6.3.0
```

**Comment by SamVerschueren** [comment]
Might be related with #7

**Comment by SamVerschueren** [comment]
I don't believe this is related with that issue but it is related with the `console.log`. Can you remove that `console.log` and try again and see if it still prints `Task 1` twice?

If you want output from a task, you'll have to use observables for that. Take a look at the [documentation](https://github.com/SamVerschueren/listr#observable).

**Comment by SamVerschueren** [comment]
Closing this for now. If you still think it's an issue, or want to discuss a little more, please let me know and I'll reopen.

**Comment by YurySolovyov** [comment]
@SamVerschueren not sure if it is useful, but yes, dropping `console.log` helps.
