### ISSUE TITLE
Ugly output on task failure

### ISSUE THREAD

**Issue by isitreallyalive** [SamVerschueren/listr#158]
I am throwing an error in my task, as so.

![image](https://user-images.githubusercontent.com/19301186/147035859-25e77860-e75b-466e-a989-646c618248c4.png)

And as you can see, I am receiving ugly output as a result - for some reason the stack trace is coming through alongside everything else, on top of the expected behaviour from Listr.

![image](https://user-images.githubusercontent.com/19301186/147035748-90b71f39-e797-47bf-a37a-a6e93c68e3b5.png)

 I have made no changes to Listr's configuration, why could this be happening?

**Comment by jzillmann** [comment]
Had the same problem. Finally switched to v2: https://github.com/cenk1cenk2/listr2
