### ISSUE TITLE
Parallel Tasks

### ISSUE THREAD

**Issue by southpolesteve** [SamVerschueren/listr#18]
Great lib! I'm running into a few cases where I would like to execute tasks in parallel. Would be great if there was support for this. One idea is options object to the `Listr` constructor function such as `{ parallel: true }`. I'm working right now to see if I can hack this together or drop down to `ora` and do it just with that lib. Will report back here if I find a good solution.

**Comment by SamVerschueren** [comment]
Shouldn't be that difficult to implement. There already is an options object so you only have to add `parallel` to it which is `false` by default. If it is set to `true`, you can use `Promise.all` to execute them at the same time.

You should be able to set it on nested `Listr` objects as well so you could execute only the subtasks of one task in parallel and the others serially.
