### ISSUE TITLE
Allow nestable subtasks

### ISSUE THREAD

**Issue by jamestalmage** [SamVerschueren/listr#2]
It would be cool if you could return a `Listr` instance from a task, and have all the subtasks display temporarily, then collapse when complete.

**Comment by SamVerschueren** [comment]
This would be very nice. I had three possibilities in mind for this.

1. Assign a tasks array to the `task` property

```js
const tasks = new Listr([
    {
        message: 'Foo',
        task: [
            {
                message: 'Bar',
                task: () => Promise.resolve('bar')
            }
        ]
    }
]);
```

2. Assign a `listr` object to the `task` property

```js
const subTask = new Listr([
     {
         message: 'Bar',
         task: () => Promise.resolve('bar')
     } 
]);

const tasks = new Listr([
    {
        message: 'Foo',
        task: subTasks
    }
]);
```

3. Let the task function return a `listr` object

```js
const subTasks = new Listr([
     {
         message: 'Bar',
         task: () => Promise.resolve('bar')
     } 
]);

const tasks = new Listr([
    {
        message: 'Foo',
        task: () => subTasks
    }
]);
```

I'm more in favour of number 3 because it offers the most flexibility. For instance, depending on the input of the user, you can choose to only run the subTasks. And why I prefer 3 over 2 is because the function lets you determine, depending on user input, if you want to run the subtasks or not. For example

```js
const subTasks = new Listr([
     {
         message: 'Bar',
         task: () => Promise.resolve('bar')
     } 
]);

const tasks = new Listr([
    {
        message: 'Foo',
        task: () => {
            if (opts.subtasks) {
                return subTasks;
            }
        }
    }
]);
```

// @sindresorhus @kevva

**Comment by sindresorhus** [comment]
3

**Comment by jamestalmage** [comment]
3. It's consistent with the current API

**Comment by SamVerschueren** [comment]
Alright, 3 it will be :)

**Comment by SamVerschueren** [comment]
I implemented it (locally) but could use your feedback. Is the `+` sign ok as symbol/icon for an open task? Or should I use something else? Maybe you guys have some ideas.

![listr](https://cloud.githubusercontent.com/assets/1913805/16126897/7b862dba-33fa-11e6-950b-74bcb9ea05cf.gif)

**Comment by jamestalmage** [comment]
My only other thought would be to have spinners at the current task, and all parent tasks. I would be interested to see what that looks like.

**Comment by SamVerschueren** [comment]
@jamestalmage Sure! :)

![listr](https://cloud.githubusercontent.com/assets/1913805/16129666/ed90f25e-3405-11e6-998a-05eea72f7e0b.gif)

**Comment by SamVerschueren** [comment]
It feels like too much animation :p.

**Comment by jamestalmage** [comment]
IDK, it looks pretty good to me.

If it's a big long list, I think it helps draw your eye to the important parts.

Maybe there is something better than `+` that would do that without the animation. A yellow ➡️ ?

**Comment by SamVerschueren** [comment]
Here are a couple of examples. 

![listr-pointer](https://cloud.githubusercontent.com/assets/1913805/16142332/a1d497d0-3464-11e6-99fe-534ccbfe59d1.gif)
![listr-pointer-small](https://cloud.githubusercontent.com/assets/1913805/16142335/a49d0bf0-3464-11e6-8e72-237fef49c1dd.gif)
![listr-arrow-right](https://cloud.githubusercontent.com/assets/1913805/16142337/aab4836a-3464-11e6-9efd-2b6fabb09a33.gif)

In the previous examples, I made the spinner `yellow` as well. Here is an example with the spinner being `gray`.

![listr-pointer-gray](https://cloud.githubusercontent.com/assets/1913805/16142377/0acd2072-3465-11e6-9db1-ea0e03a239b4.gif)

Feedback more then welcome :).

**Comment by SamVerschueren** [comment]
I went with the first example with the yellow `❯` and yellow spinner. Always happy to change it later on.
