### ISSUE TITLE
Passing a `context` object to the task functions

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/listr#20]
In #17, the idea came up for passing a `context` object as argument of a task function. This would allow you to pass data from one task to another allowing you to create composable tasks.

Do we have to take something special into account when doing this? Because we are targetting Node 4+, are there any reasons why we should pass in a regular `Object.create(null)` object instead of `Map`?

**Comment by otbe** [comment]
Hi @SamVerschueren
any chances to see this merged soon? What be awesome to use the output of a task in a successor task :)

Thanks for listr!

**Comment by SamVerschueren** [comment]
Will try to prioritize this. Thanks for the interest :).
