### ISSUE TITLE
Any way to preserve colors in the output?

### ISSUE THREAD

**Issue by okonet** [SamVerschueren/listr#23]
I'm trying to incorporate this module to lint-staged: https://github.com/okonet/lint-staged/pull/32
and running into a few issues. I'd like to have all errors from subsequent tasks (i.e. linters) be outputted to the console "as is". 

So, the "right" way of doing it ATM is like:

```js
return new Promise((resolve, reject) => {
                        execa(res.bin, res.args)
                            .then(() => {
                                resolve(`${linter} passed!`)
                            })
                            .catch(err => {
                                reject(`
🚨  ${linter} found some errors. Please fix them and try committing again.

${err.stdout}
`
                                )
                            })
                    })
```

See https://github.com/okonet/lint-staged/blob/47099e87d059f79ebc7d8bbe5c0e80069704f5bf/src/runScript.js#L14-L27

This works fine, but the output looses all the colors. This sucks!

To preserve colors, it seems there is no other way as spawning a process with `stdio: "inherit"` option passed in. This makes output colored, but at the same time breaks the output of this module. It now appears twice and (worst thing) it cuts some of the stdout output from the task.

<img width="818" alt="2016-07-23 at 11 37" src="https://cloud.githubusercontent.com/assets/11071/17077266/ee79f428-50c9-11e6-8e56-d49b25f3e075.png">

I'm wondering what would be a better work around this.

See also #16

**Comment by SamVerschueren** [comment]
It looks like I missed this one. The reason the color is not shown is because I use [strip-ansi](https://github.com/chalk/strip-ansi) [here](https://github.com/SamVerschueren/listr/blob/master/lib/task.js#L84). Why? Because I thought the ANSI escape codes caused a bug, which I now believe wasn't the cause of the escape codes. So I think we can safely bring this back.

**Comment by okonet** [comment]
👏👏👏

**Comment by SamVerschueren** [comment]
I believe this should work again. Care to check it out? I don't `strip-ansi` the output anymore. Closing this for now, please let me know if it didn't fix it.

**Comment by okonet** [comment]
It works if I set a command to run with colors explicitly but not if it's coming from `stdout`. BTW this also worked with v0.4.3 as well. I believe this is the node limitation but not sure either.

**Comment by SamVerschueren** [comment]
I believe node is stripping the ANSI escape codes then and just returning a "clean" string that can be rendered to the output.

**Comment by okonet** [comment]
So do you think this can be work around? I could not find anything yet.

**Comment by SamVerschueren** [comment]
If you would go for the `verbose` renderer, I believe you can use `stdio: 'inherit'`. But off course, that renderer is quite basic. I don't really see a solution to be honest for it to work in the default (log updated) renderer.

// @sindresorhus @jamestalmage

**Comment by okonet** [comment]
Hmm, even with https://github.com/SamVerschueren/listr-verbose-renderer it's not colored.

**Comment by SamVerschueren** [comment]
Did you pass `stdio: 'inherit'`?

From your initial post:

> To preserve colors, it seems there is no other way as spawning a process with stdio: "inherit" option passed in. This makes output colored, but at the same time breaks the output of this module. 

So instead of logging `err.stdout` yourself, let `execa` do it for you.

**Comment by okonet** [comment]
Here is the related SO post: http://stackoverflow.com/questions/9135579/node-js-spawn-with-colors#9137636

**Comment by okonet** [comment]
I'll try to write a custom renderer that will not continue after an error and use execa with stdout. I'll let you know here. Thanks for your support!

**Comment by okonet** [comment]
I was able to solve this issue by this commit: https://github.com/okonet/lint-staged/commit/7684fa8529113ea6be378ac97668aaff88b342f3

**Comment by SamVerschueren** [comment]
Cool, good to know!
