### ISSUE TITLE
Show all subtasks

### ISSUE THREAD

**Issue by bfred-it** [SamVerschueren/listr#25]
Currently subtasks are hidden once they're done. It'd be nice to leave them on once they're done, as an outline of the process. For example instead of:

> - Prerequisite check
> - Git
> - Installing dependencies
> - Publishing package
> 
> Done

It could be a more explicative:

> - Prerequisite check
> 	- Validate version
> 	- Check for pre-release version
> 	- Check npm version
> 	- Check git tag existence
> - Git
> 	- Check current branch
> 	- Check local working tree
> 	- Check remote history
> - Installing dependencies
> - Bumping version
> - Publishing package
> 
> Done

**Comment by SamVerschueren** [comment]
When running the tasks, they will all be collapsed though. So it will still start like this:

> - Prerequisite check
> - Git
> - Installing dependencies
> - Publishing package
> 
> Done

But I agree, it might be a nice addition to not close the subtasks. Any suggestion for an option name?

**Comment by bfred-it** [comment]
Sure, the list could expand as it discovers (sub-)tasks.

I'd say `collapseSubtasks` or `collapseEndedSubtasks` defaulting to `true`

**Comment by SamVerschueren** [comment]
This is now possible in `master` with the `collapse` flag since the renderers are now loosly coupled. The flag is part of the [listr-update-renderer](https://github.com/SamVerschueren/listr-update-renderer).
