### ISSUE TITLE
The observable interface no longer contains the forEach method

### ISSUE THREAD

**Issue by TylorS** [SamVerschueren/listr#27]
The Observable interface as defined [here](https://github.com/tc39/proposal-observable#observable)
No longer contains the method `forEach()` which is used to determine if an object returned by a task is an observable [here](https://github.com/SamVerschueren/listr/blob/master/lib/task.js#L21).

I'd propose adjusting that line to something like
```js
const isObservable = obj => obj && typeof obj.subscribe === 'function' && typeof obj.constructor.from === 'function'
```

I don't forsee the `from()` static method being removed since it's the basis for converting to and from different observable types. 

I'd be happy to PR this if it would be accepted. 

Thank you for you time :smile:

**Comment by SamVerschueren** [comment]
I guess you're right. PR welcome! :)
