### ISSUE TITLE
0.6.0 broke default rendering

### ISSUE THREAD

**Issue by andywer** [SamVerschueren/listr#29]
Hey @SamVerschueren, I am glad for the new renderers!

But I just experienced an issue when trying to use 0.6.0 for npm-launch. Seems like it doesn't render much anymore when using the default renderer. Maybe it's rendering the listr instance as `completed` before it actually is?

![listr-0 5 0](https://cloud.githubusercontent.com/assets/1842462/18577202/1ee0427c-7be8-11e6-98dc-4800f4700e92.gif)

![listr-0 6 0](https://cloud.githubusercontent.com/assets/1842462/18577206/244eb504-7be8-11e6-8647-0d8b41ac432f.gif)

**Comment by SamVerschueren** [comment]
That's odd... Could you provide a minimal example with the same behaviour? I tested quite some use cases but never experienced this issue.

**Comment by andywer** [comment]
I think it happens when the task returns an Observable.

Here is a minimal example: https://gist.github.com/andywer/11855be9cb700be4ddae520b3330437e

Btw: It also happens without the `concurrent` option.

**Comment by SamVerschueren** [comment]
It works with the example here in this repo. I did change the [isObservable](https://github.com/SamVerschueren/listr/blob/master/lib/task.js#L11) check though. What Observable library do you use? Care to take a look at it? I'm leaving this weekend on a weekend trip so don't have much time to look into it.

**Comment by andywer** [comment]
I am using https://github.com/zenparsing/zen-observable, since it's very small and straight-forward.

I can have a look if your `isObservable` works with the zen-observable lib :)

**Comment by andywer** [comment]
Already have a result :)

`obj.constructor.create` is undefined on my zen-observable Observable.

**Comment by andywer** [comment]
Btw: https://github.com/tc39/proposal-observable shows the Observable's minimal interface. RxJS 5 and zen-observable are also both listed as implementations of this draft spec.

Maybe check for `Observable.from` and `Observable.of`, instead of `Observable.create`?

`const isObservable = obj => obj && typeof obj.subscribe === 'function' && typeof obj.constructor.from === 'function' && typeof obj.constructor.of === 'function';`

**Comment by SamVerschueren** [comment]
Tried it with `from` but didn't work. Will fix it asap. Also have to write tests with different observable libraries to prevent regression.

PR always welcome as well :).

**Comment by andywer** [comment]
Opened PR: #30 :)

**Comment by SamVerschueren** [comment]
Thanks for looking into this!
