### ISSUE TITLE
rename `message` to `title`

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/listr#3]
Currently a task is defined by `message` and `task`. We should change `message` to `title` it seems more appropriate.

**Comment by megalithic** [comment]
@SamVerschueren, please update the README's usage section to reflect this change.

**Comment by megalithic** [comment]
@SamVerschueren looks like [3703ce9](https://github.com/SamVerschueren/listr/commit/3703ce91b180a7df9f9b03b51023ad75ad82415a) never got published.

<img src='https://www.dropbox.com/s/nes286xq5m6r4j7/Screenshot%202016-06-26%2023.37.42.png?dl=0' />

**Comment by SamVerschueren** [comment]
@megalithic You're right, I wanted to fix #1 first but it's not a quick implementation so I released `0.2.0`.
