### ISSUE TITLE
hit enter when running listr will get the same duplicated output as using `console.log`

### ISSUE THREAD

**Issue by vivaxy** [SamVerschueren/listr#38]
![image](https://cloud.githubusercontent.com/assets/4216856/20783283/ccb0c892-b7cd-11e6-9970-a4708b4cc3c6.png)

**Comment by SamVerschueren** [comment]
I don't think we can actually do something about that. Have to check though if the enter could be catched by `log-update`.

@sindresorhus Any ideas?

**Comment by vivaxy** [comment]
I have looked into `log-update`, it has the `enter` pressing problem.

And I tried to fix it by adding this before running a listr:

```js
const keypress = require('keypress');
const stdin = process.stdin;
keypress(stdin);
stdin.setRawMode(true);
stdin.resume();
stdin.setEncoding('utf8');
stdin.on('keypress', (ch, key) => {
	if (key && key.ctrl && key.name === 'c') {
		process.exit(0); // should mimic `<ctrl>-c`
	}
});
// should setRawMode to false after listr
```

I am looking for a better solution.

**Comment by sindresorhus** [comment]
Yes, you would have to enable raw mode, which disables all other default behavior. I don't think it's worth doing that.

**Comment by SamVerschueren** [comment]
I agree with Sindre. If someone presses enter, then he presses enter. It's really an edge case and doesn't appear on normal use.

**Comment by vivaxy** [comment]
Actually, I am not expecting someone to mess up `listr` rendering. I think I am just gonna add this feature into my own project. Thanks for your advices.
