### ISSUE TITLE
Fails on non-string output

### ISSUE THREAD

**Issue by legodude17** [SamVerschueren/listr#40]
`listr` will throw an error when an observable task outputs something without a `.trim()` method, like a number or object. Test case:
```js
const tasks = new Listr([{
  title: 'Count',
  task: () => {
    title: 'Count up',
    task: () => rx.Observable.create(obj => {
      var i = 0;
      var id = setInterval(() => obj.next(i++), 100);
      setTimeout(() => {clearInterval(id); obj.complete(i)}, 1050);
}}]);

**Comment by SamVerschueren** [comment]
Good point! Haven't thought about it.

**Comment by SamVerschueren** [comment]
Fixed (https://github.com/SamVerschueren/listr-update-renderer/issues/3) and released. It should work now after reinstalling `listr`.

**Comment by legodude17** [comment]
Thanks!
