### ISSUE TITLE
Rejecting with a string as argument shows an error

### ISSUE THREAD

**Issue by okonet** [SamVerschueren/listr#41]
In lint-staged I'm rejecting a promise with a String as docs says here https://github.com/SamVerschueren/listr#promises

But when doing so I get the following output:

```
{ TypeError: Cannot create property 'context' on string '
🚫 pwd found some errors. Please fix them and try committing again.



'
    at tasks.then.catch.err (/Users/okonet/Projects/OSS/sort-staged-example/front/node_modules/listr/index.js:74:17)
    at process._tickCallback (internal/process/next_tick.js:103:7) context: {} }
```

Note that before it was displaying and this is the correct behavior:

```
🚫 pwd found some errors. Please fix them and try committing again.
```

I think this is due to this one: https://github.com/SamVerschueren/listr/commit/72ee8cc0331f537e79f7a58ae13e48c48150eae6 (https://github.com/SamVerschueren/listr/issues/37)

**Comment by SamVerschueren** [comment]
Good point. I'm uncertain about the solution though. It's bad practice to reject literal values like strings directly as they should be wrapped inside an `Error` object.

So we can have 2 solutions here.
1. Fix documentation and reject with `new Error()` instead
2. Check the error type and if it's not an object, wrap the error inside a `new Error()` call

@sindresorhus Any feedback on this? I remember this came up in [AVA](https://github.com/avajs/ava) as well and that we decided to not wrap the thrown values.

**Comment by okonet** [comment]
Rejecting with an `Error` will also break how things are displayed in the CLI. So right now I'm doing `console.error(error)`. I guess I'll need to log just the message then?

**Comment by sindresorhus** [comment]
1.

**Comment by SamVerschueren** [comment]
@okonet Exactly, it should be `console.error(error.message)` instead.

@sindresorhus Thanks!

Let's update the documentation then and suggest people to reject with an `Error` object instead.
