### ISSUE TITLE
Add `enabled` property to a task

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/listr#42]
From https://github.com/sindresorhus/np/pull/114#discussion_r96590970

It would be nice if we could dynamically make tasks visible or invisible. If invisible, they shouldn't be executed. So maybe the property should be called `enabled` instead? I had something in mind like

```js
const tasks = new Listr([
    {
        title: 'Install with yarn',
        task: ctx => execa('yarn')
                .catch(() => {
                        ctx.yarn = false;
                });
    },
    {
        title: 'Install with npm',
        visible: ctx => ctx.yarn === false,
        task: () => execa('npm', ['test'])
    }
]);
```

The function should be synchronous because otherwise we could end up in a state where it looks like the tasks aren't doing any work for 5 seconds for instance.

While I'm typing this, I might be more in favour if `enabled`. As `visible` might look like the task is invisible but it will still be executed.

Any remarks, improvements or things I overlooked? Feel free to provide feedback.

// @sindresorhus

**Comment by sindresorhus** [comment]
> So maybe the property should be called enabled instead?

👍
