### ISSUE TITLE
Support skipping a task while performing the main function

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/listr#43]
From https://github.com/sindresorhus/np/pull/114#discussion_r96590970

It should be possible to skip a task from the main function. Not sure about the implementation details though. We can't use `this.skip('message')` inside the `task` function because they don't play nice with fat-arrow functions. So maybe a second 'task' object as argument?

```js
const tasks = new Listr([
    {
        title: 'Install with yarn',
        task: (ctx, task) => execa('yarn')
                .catch(() => {
                        task.skip('Yarn is not available on your system');
                });
    },
]);
```

Feedback much appreciated!

// @sindresorhus

**Comment by sindresorhus** [comment]
> So maybe a second 'task' object as argument?

👍

**Comment by SamVerschueren** [comment]
With the `task` object, we could also change the title dynamically which might be a nice feature as well.

```js
const tasks = new Listr([
    {
        title: 'Installing dependencies with Yarn',
        task: (ctx, task) => execa('yarn')
                .catch(() => {
                        task.setTitle('Installing dependencies with npm (Yarn is not available)');

                        return execa('npm', ['install']);
                });
    },
]);
```

@gillchristian Feel free to provide feedback. I'm trying to come up with the best solution possible to fix https://github.com/sindresorhus/np/pull/114

**Comment by sindresorhus** [comment]
> With the task object, we could also change the title dynamically which might be a nice feature as well.

That could indeed be useful. Although I would prefer a setter: `task.title = 'Unicorn unicorn unicorn';`.

**Comment by SamVerschueren** [comment]
> Although I would prefer a setter: task.title = 'Unicorn unicorn';.

👍

**Comment by SamVerschueren** [comment]
Implementing this is quite simple. I'm just wondering how the [verbose renderer](https://github.com/SamVerschueren/listr-verbose-renderer) should respond to a change in the title. It should be non-TTY friendly.

**Comment by sindresorhus** [comment]
Maybe

```
New title [title changed]
```

**Comment by SamVerschueren** [comment]
Was thinking in the same fashion. Going for that. I can always update that renderer afterwards if someone comes up with a better notation.

**Comment by SamVerschueren** [comment]
I implemented the task object in PR https://github.com/SamVerschueren/listr/pull/44. Feel free to provide feedback. I'm probably going to merge it tomorrow.

The task object lets you do two things
1. Skip a task while executing the task function
2. Change the title while executing the task function
