### ISSUE TITLE
Status icons in Windows 7 command line tool

### ISSUE THREAD

**Issue by scriptPilot** [SamVerschueren/listr#45]
Maybe I do it wrong, but if I open Windows command line with `cmd` and run the following JS script with `node script.js`, I got instead of success status icons only **V**.

````
const execa = require('execa');
const listr = require('listr');

const tasks = new listr([
    {
        title: 'Task 1',
        task: () => Promise.resolve('Foo')
    },
    {
        title: 'Can be skipped',
        skip: () => {
            if (Math.random() > 0.5) {
                return 'Reason for skipping';
            }
        },
        task: () => 'Bar'
    },
    {
        title: 'Task 3',
        task: () => Promise.resolve('Bar')
    }
]);

tasks.run().catch(err => {
    console.error(err);
});
````

**Comment by SamVerschueren** [comment]
It's because Windows does not support unicode. So that icon is a fall back, nothing we can do about it.

**Comment by SamVerschueren** [comment]
The package used is `log-symbols` and you can see the fallback mechanism [here](https://github.com/sindresorhus/log-symbols/blob/master/index.js#L13).

**Comment by scriptPilot** [comment]
Ok, thanks
