### ISSUE TITLE
Promise returning an Obsevable

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/listr#5]
The case where a promise returns an observable is not handled at the moment which means that something like this

```js
const task = {
    title: 'Clean & Install',
    task: () => del('node_modules').then(() => exec('npm', ['install'])))
};
```

Where `exec` returns an `execa` `Observable` ends the task after removing the `node_modules`.

**Comment by jamestalmage** [comment]
👍 I actually need something like this now.

**Comment by SamVerschueren** [comment]
🎉
