### ISSUE TITLE
Add Task on the run

### ISSUE THREAD

**Issue by JbIPS** [SamVerschueren/listr#50]
Hi,

I'm having a slightly different use case: I would like to add task to Listr while it's already running (my task list is unknown when the program start).

On my first tries, the 2nd task is rendered but the spinner never shows and the list complete before the return of the second promise. My guess is that it use a [`reduce`](https://github.com/SamVerschueren/listr/blob/master/index.js#L83) to run the tasks and it won't accept new entries while reducing.

I'm working on a recursive approach that would `shift` the array until `null`. Do you think it can work? Any advice? Thanks

**Comment by parro-it** [comment]
I'm doing something similar just, now: it work very well!

I hope it can help you:

```js
'use strict';
const Listr = require('listr');
const config = require('./config');
const {
	connect,
	getSaveableMeasures,
	convertToMeasureValues,
	saveMeasures,
	updateMeasureState
} = require('.');

const pool = connect(config);
const tasks = new Listr([{
	title: 'Find unsaved measures',
	task: async ctx => {
		ctx.unsavedMeasures = await getSaveableMeasures(pool);
	}
}, {
	title: 'Saving measures',
	task: ctx => {
		const savingProcedures = ctx.unsavedMeasures.map(({year, code, results}) => ({
			title: code,
			task: async() => {
				const measures = convertToMeasureValues(results, 4242, year);
				await saveMeasures(measures, pool);
				await updateMeasureState(code, 'Caricata', pool);
			}
		}));
		return new Listr(savingProcedures);
	}
}, {
	title: 'All measures saved',
	task: () => pool.close()
}]);

tasks.run().catch(err => {
	console.error(err);
});
```

Output:

![image](https://cloud.githubusercontent.com/assets/11197111/22510676/1cba570e-e893-11e6-9a61-fdb7e4b9a7b8.png)

**Comment by JbIPS** [comment]
If I understand correctly, you still create the subtask list *before* running it. That may be a lead but I don't think it will be enough for my use case.

BTW, how come `All measures saved` popped up before all measures were checked?

Thank you

**Comment by parro-it** [comment]
> If I understand correctly, you still create the subtask list before running it

Exactly, they are created in 'Saving measures' task. 
There, I return another `Listr` instance containing all subtasks.

> BTW, how come All measures saved popped up before all measures were checked?

1) Here "Find unsaved measures" is running: subtasks are not yet known:

![image](https://cloud.githubusercontent.com/assets/11197111/22511158/01f82b9c-e895-11e6-99d5-e83ef54c412d.png)

2) Here I return the new `Listr` instance. Please note that "Saving measures" node is now expanded. "All measures saved" node it's not still executed.

![image](https://cloud.githubusercontent.com/assets/11197111/22511181/16f06a3c-e895-11e6-987e-4caa3347bd9b.png)
![image](https://cloud.githubusercontent.com/assets/11197111/22511209/2d6225c6-e895-11e6-958b-45729acc3dad.png)


3) Process completed: "Saving measures" node is now shrinked again:

![image](https://cloud.githubusercontent.com/assets/11197111/22511308/8f2e1e68-e895-11e6-8c61-678a2e909e21.png)

**Comment by JbIPS** [comment]
I understand, I misread between *listed* and *executed*.

Here's a basic example of my use case:
```
'use strict';
const Listr = require('.');

var list = new Listr([]);

let i = 0;
var interval = setInterval(() => {
		list.add({
		title: 'Test '+i,
		task: () => {
			return new Promise((resolve, reject) => {
				setTimeout(resolve, 2000);
			});
		}
	});
	if(i == 0) list.run();
	else if(i == 4) {
		list.add({
			title: 'Sub',
			task: () => {
				return new Listr([
					{
						title: 'sub1',
						task: () => {
							return Promise.resolve();
						}
					},{
						title: 'sub2',
						task: () => {
							return new Promise((resolve, reject) => {
								setTimeout(resolve, 2000);
							});
						}
					}
				]);
			}
		});
		clearInterval(interval);
	}
	i++;
}, 500);
```
This could be achieve with very few modification: https://github.com/JbIPS/listr/commit/f0fa0cd3cfae26613fd5b5d75e6f55bd27402397

**Comment by SamVerschueren** [comment]
Not sure if this is a fit for `Listr` to be honest. If all of this is dynamic, you might be better of with [Ora](https://github.com/sindresorhus/ora).

The thing I'm most concerned about is this. What if we define Listr with one task that takes 2 seconds to execute. After 1 second we add another task which takes 1 second to execute. This makes a total of 3 seconds of execution. What if we waited for another 4 seconds and tried to add another task. This means that the 2 previous tasks are already entirely executed and listr has stopped executing.

I like how @parro-it solved his use case. We actually needed a "dynamic" task in [np](https://github.com/sindresorhus/np) which might use come up with [the possibility of enabling or disabling a task](https://github.com/SamVerschueren/listr#enabling-tasks) and also [adding the possibility of dynamically chaning the tasks title](https://github.com/SamVerschueren/listr#task-object).

It really looks and feels like Listr was not designed for this. Feel free to provide feedback on my remarks.

**Comment by JbIPS** [comment]
> you might be better of with Ora.

You're right, I started with Ora, but ironically **you** [brought me here](https://github.com/sindresorhus/ora/issues/31) 😄 

I understand your concerns and IMHO the user is responsible for adding new tasks before ending the last one. Since it was only a addition and don't break compatibility with the existing code I though it could be a nice feature but maybe I'll stick with Ora. Or do you have another idea?

Thanks

**Comment by SamVerschueren** [comment]
Hi @JbIPS, sorry for the late reply.

Sorry that the link brought you here ;). I think it's really use case dependent if Listr is a good fit or not. I answered that thread because it looked like the topic starter could benefit from all the things Listr covers. If you know all your things beforehand, then Listr is a perfect fit. If you could defer task creation like @parro-it did and run it in a subtask, then Listr is a perfect fit. But if everything is dynamically, I think Listr isn't a perfect fit and you might be better of with Ora because then you can just run task after task dynamically and you have more flexibility.

I'm closing this feature request for now. I'm still open for discussion though. So if other people want to chime in on this one, go ahead.

**Comment by petemill** [comment]
I have a similar use case, but there is a difference which perhaps leads to framing this a more acceptable way.

Use case is that I know the tasks ahead of time, I want to run them concurrently but only X at a time. When 1 task finishes, I can run a newer one. (More specifically, when updating dynamodb tables you can do 5 at a time).

I tried adding the first 5 tasks, then after each finishes, adding a new task, but obviously listr does not like having tasks added after run() is called. I can add all the tasks ahead of time but then I can't have `concurrent: true`. What could work is a combination of `enabled: () => Observable` and concurrency, or a `task.run()` function. At which point I could dynamically run tasks as long as I know them ahead of time.

I understand that there would be edge cases in what I'm proposing, in that you could get in to a state where `run()` never resolves, so this probably isn't the right solution.

**Comment by petemill** [comment]
...oh... basically what @alexpsi is suggesting on https://github.com/SamVerschueren/listr/pull/56!
