### ISSUE TITLE
Improve arguments handling

### ISSUE THREAD

**Issue by kaatt** [SamVerschueren/listr#59]
For the longest time, I was debugging an issue which was finally fixed by replacing:
```
new Listr({
    title, task
}, {
    title, task
})
```
with
```
new Listr([{
    title, task
}, {
    title, task
}])
```
Notice the difference? Listr wasn't doing anything in the first instance, I couldn't think of anything better to say than "it doesn't work", no output, no errors, nothing, just a no-op... and so it took so long to debug.

**Comment by okonet** [comment]
I guess the best way to fix this would be a PR. It seems pretty straightforward to fix.

**Comment by SamVerschueren** [comment]
The thing is that you can also pass in an options object without tasks.

```js
const listr = new Listr({
    concurrent: true,
    exitOnError: false
});

listr.add({
    title: 'My custom task',
    task: () => Promise.resolve('foo')
});
```

So yes, maybe we could solve this by detecting if the input is an object and has the property `title` and `task`. If that is the case, throw an error.
