### ISSUE TITLE
List is sometimes pushed up

### ISSUE THREAD

**Issue by sindresorhus** [SamVerschueren/listr#7]
When running `np` on https://github.com/sindresorhus/sindre-playground the list jumps up when "Running tests" is showing output. It should rather push the list down.

![bug](https://cloud.githubusercontent.com/assets/170270/16633341/1d2c86fe-43c9-11e6-9949-c3c5fc81754f.gif)

**Comment by SamVerschueren** [comment]
You're right, not sure why though. Some edge case in log-update perhaps?

**Comment by sindresorhus** [comment]
Dunno. Maybe you're not outputting the same height and it makes it scroll up.

**Comment by SamVerschueren** [comment]
Is it necessary to always log the some height? Because I'm not doing that currently

**Comment by sindresorhus** [comment]
I think so. If you suddenly log something that is 1 row higher, it will jump by one.

**Comment by SamVerschueren** [comment]
Ok, that might be a problem because of nested lists. A nested list can suddenly add 4 extra lines.

**Comment by sindresorhus** [comment]
@SamVerschueren I'm not totally sure though. It's a long time since I wrote `log-update`. You might wanna double-check first.

**Comment by SamVerschueren** [comment]
Yes I will definitely will and will dive deeper into the internals of the module.

**Comment by SamVerschueren** [comment]
I think the reason for this behaviour is when the strings are being printed that are long then the width of the terminal. The terminal auto-wraps those lines and I think `log-update` only counts that line as being `1` instead of `2` (if it wrapped on 2 lines). Does that sounds logical or not really :p? 

![listr-bug](https://cloud.githubusercontent.com/assets/1913805/16687817/05616a82-451b-11e6-9a5d-7213b1c65089.gif)

**Comment by sindresorhus** [comment]
I think both. You should use [cli-truncate](https://github.com/sindresorhus/cli-truncate) or something to cut it off, but should still be fixed in `log-update` for other use-cases. Sounds like [this one](https://github.com/sindresorhus/log-update/issues/10) (Although a poorly written issue).

**Comment by SamVerschueren** [comment]
Yes, needs to be fixed in `log-update` as well. Will try to find a solution.

**Comment by jamestalmage** [comment]
Look at the mini reporter in AVA. It does other things as well, but it does address this issue.

**Comment by sindresorhus** [comment]
@jamestalmage Are you referring to [this part](https://github.com/avajs/ava/blob/6c0f093612b9fc484161a02b22ec3304cfe86627/lib/reporters/mini.js#L285-L304)?

**Comment by jamestalmage** [comment]
Yes - and [this part](https://github.com/avajs/ava/blob/6c0f093612b9fc484161a02b22ec3304cfe86627/lib/reporters/mini.js#L242-L252) which handles line wraps, and lines that end **exactly** on the last column (which messes up one of the supported terminals, OSX terminal I believe?).

I forget exactly what was wrong in log update, but it basically came down to inconsistent support. As I recall, something in `ansiEscapes.eraseLines` did not leave the cursor where you expected it to. I found the best way to debug it was to leave the cursor on, and add delays between each command:

```js
// Log debugger
var delay = require('delay');

var last = Promise.resolve();

function log(str) {
  last = last.then(() => {
    process.stdout.write(str);
    return delay(500);
  });
}

log('foo');
log('bar'); // happens in steps, so you see what is happening
```

It's a bit of a pain, but I found it the best way to figure out exactly what happens in each terminal.

**Comment by sindresorhus** [comment]
@jamestalmage We should bring the AVA changes back to `ansi-escapes`.

**Comment by SamVerschueren** [comment]
I added `cli-truncate` now and I believe this will fix the issue. Although `log-update` should still be fixed (in the near future). Currently not much time and I want to fix some issues in `listr` first. After that, happy to take the issue.

@sindresorhus if you need to publish a module (in the coming days), care to test it with `master` and see what it gives? If not, no problem :). I'll do as well.
