### ISSUE TITLE
Creating/updating sub-tasks dynamically

### ISSUE THREAD

**Issue by rprieto** [SamVerschueren/listr#76]
Hi,

I have a task that's made up of 1000 smaller jobs, each taking between 10ms and 1s, which are run in parallel with [`async.parallelLimit(cpuCount)`](https://caolan.github.io/async/docs.html#parallelLimit). I'd like to show the user what's happening.

For now I'm using an Observable with a multi-line renderer. The Observable outputs the names of all the jobs currently running:

```
⠧ My task
    Processing job A       \
    Processing job C        \     this is the full
    Processing job E        /     output of the observable
    Processing job F       /
```

This works great for TTY terminals, however in text-only it's very confusing as it renders the whole status every time. For example when `job C` finishes, it outputs the whole 4 lines to `stdout` again and it's hard to tell what job just finished/started.

Instead I'd like to use sub-tasks, for example:

```
> My task
   ⠧ Processing job A       \
   ⠧ Processing job C        \     each a proper Listr task 
   ⠧ Processing job E        /     over a Promise that will resolve when finished
   ⠧ Processing job F       /
```

Then in text mode it would show this, which is great for troubleshooting:

```
09:12:45 Processing job B [completed]
09:12:47 Processing job E [started]
```

The only challenge is that I can't seem to add or delete sub tasks dynamically. The reason it must be dynamically added/removed is because there could be 1000 jobs, and I don't even know which order they will be executed in since that's controlled by `async.parallelLimit`.

What's your recommendation?

**Comment by SamVerschueren** [comment]
This really depends on the use case. If inside `My task` function, all the jobs are known, I believe this might be possible in combination with the [`enabled`](https://github.com/SamVerschueren/listr#enabling-tasks) task property. You could then show/hide the tasks based on the status. If the task is still queued for instance, or if the job is finished, you could hide it, if it's unqueued and pending, you could show it.

**Comment by rprieto** [comment]
Thanks that's interesting, I'll have a look at toggling the `enabled` property dynamically. In my case I *do* know all the jobs in advance, just not the order in which they will be picked up.

**Comment by rprieto** [comment]
Fully understand! Thanks already for creating this great package. I've started updating https://github.com/thumbsup/thumbsup to use `listr` for its CLI.

**Comment by rprieto** [comment]
I've started looking at the "enabled" suggestion, but I couldn't get it to work since dynamically setting `enabled` isn't compatible with `concurrent`. In fact, I think I need something similar to https://github.com/SamVerschueren/listr/issues/53 (only rendering running tasks). 

I've implemented this locally with a really small change: a new optional `visible()` method at the task level that defaults to `visible = () => this.isEnabled()`.

```js
const task = {
  title: 'photo-1466972618291-13e16a49f5aa2.jpg',
  visible = () => this.isPending(),
  task: () => /* ... */
}
```

I then updated my renderer to use that:

```
✔ Updating database
✔ Creating model
❯ Processing media
   ⠸ photo-1466972618291-13e16a49f5aa2.jpg
   ⠹ photo-1467307983825-619715426c702.jpg
   ⠹ photo-1467663906983-81383d4802ef2.jpg
  Cleaning up
  Creating website
```

which the corresponding non-TTY output which is perfect:

```
[19:32:59] photo-1429216967620-ece20ff3a5f92.jpg [completed]
[19:32:59] photo-1431578409060-9aad91ba5f792.jpg [started]
[19:32:59] photo-1428940253195-53483a1de2e6.jpg [completed]
[19:32:59] photo-1431578409060-9aad91ba5f792.jpg [started]
[19:32:59] photo-1429216967620-ece20ff3a5f92.jpg [completed]
[19:32:59] photo-1431794062232-2a99a5431c6c2.jpg [started]
[19:32:59] photo-1431578409060-9aad91ba5f792.jpg [completed]
```

What do you think? I think it's quite powerful to allow the user to define at the task level if it should be rendered or not, and is only a couple lines change.

*Note: simply using `isPending()` in the renderer is not enough, since it would apply to all tasks, not just these particular jobs.*

**Comment by rprieto** [comment]
Thinking about it, what I'm really after is the same as #53.

In the meantime, I've setup a small package that fits my needs: https://github.com/thumbsup/listr-task-queue. The main downside is that it has to take over the orchestration from `Listr`, so I'm keen to stop using it as soon as another option is available 😄

**Comment by felixfbecker** [comment]
I have a use case for the feature described in this issue - I want to add tasks dynamically as input comes in from STDIN, then remove them from the list again when they are done.
