### ISSUE TITLE
readme woes

### ISSUE THREAD

**Issue by ORESoftware** [SamVerschueren/listr#81]
sorry I just had to LOL at this....it has happened to me before, so know that I am laughing with you not at you lol

<img width="1032" alt="screenshot 2017-11-01 13 03 16" src="https://user-images.githubusercontent.com/11139560/32294970-1259012c-bf05-11e7-8d11-2f379e7d7be0.png">

maybe try .editorconfig to get the spacing less extreme, lol idk

**Comment by ORESoftware** [comment]
lol

**Comment by SamVerschueren** [comment]
https://github.com/SamVerschueren/listr/blob/master/.editorconfig
