### ISSUE TITLE
Observable on a loop

### ISSUE THREAD

**Issue by Rawnly** [SamVerschueren/listr#83]
When i run the following code: 
```js
const tasks = new Listr([
	{
		title: 'download',
		task: () => {
			return Observable.create(async observer => {
				let {photos, title} = await collectionDownloader(562095);

				photos.forEach(async ({url, id}, index) => {
					let pth = join(__dirname, title);
					mkdp.sync(pth);
					pth += `/${id}.jpg`;

					const file = fs.createWriteStream(pth);

					https.get(url, response => {
						response.pipe(file).on('finish', () => {
							observer.next(`Downloading ${index + 1} of ${photos.length} photos from ${title}`);
							file.close();
						});
					});

					if (index === photos.length) {
						return observer.complete();
					}
				});
			});
		}
	}
]);

tasks.run();
```

i get this: 
![2017-12-03 03 41 48](https://user-images.githubusercontent.com/16429579/33521774-0434db6c-d7dc-11e7-9f3a-fa3ce5d5ba88.gif)

## The problem
1) it never ends.
2) the index is not correctly shown.. is not ordered and it starts when all downloads are done..

Please tell me what I'm doing wrong.

**Comment by SamVerschueren** [comment]
Probably because `index` is zero based and `photos.length` is one based. So basically, you're checking `14 === 15`.

Support questions are better asked on StackOverflow. This has (probably) nothing to do with Listr itself.
