### ISSUE TITLE
Should use more common subscribe method signature

### ISSUE THREAD

**Issue by jamestalmage** [SamVerschueren/listr#9]
You are currently using `observable.subscribe(onNext, onError, onComplete)`, but that seems to be an RxJx specific thing.

You should use an observer object instead. That way people can still supply `zen-observable` observables if they wish. https://github.com/zenparsing/zen-observable#observablesubscribe--observer-

**Comment by SamVerschueren** [comment]
Oh, I did not know that. Thanks for the information!

**Comment by SamVerschueren** [comment]
That doesn't seem to work for `RxJS` :(. It looks like it really expects an `Observer` object.

```js
var observer = Rx.Observer.create(
  function (x) {
    console.log('Next: %s', x);
  },
  function (err) {
    console.log('Error: %s', err);
  },
  function () {
    console.log('Completed');
  });
```

https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/subscribe.md

**Comment by SamVerschueren** [comment]
Strange, I looked at it again and if I pass the following object as observer (documented by zen-observable)

```js
const observer = {
    next(x) { console.log(x) },
    error(err) { console.log(`Finished with error: ${ err }`) },
    complete() { console.log("Finished") }
};
```

That doesn't work, but when I pass this object as an observer:

```js
const observer = {
    next: x => { console.log(x) },
    error: err => { console.log(`Finished with error: ${ err }`) },
    complete: () => { console.log("Finished") }
};
```

That works. I thought both where identical, no?

**Comment by SamVerschueren** [comment]
Thanks for this @jamestalmage! Fixed now.

**Comment by jamestalmage** [comment]
That is super weird. Open an issue with RxJS
