### ISSUE TITLE
Passing context to sub-listr tasks

### ISSUE THREAD

**Issue by aequasi** [SamVerschueren/listr#92]
Something like:

```javascript
new Listr([
	{
		title: 'start',
		task: (ctx) => {
			ctx.baz = 'foobar';
		}
	},
	{
		title: 'Something',
		task: (ctx) => {

			return new Listr([
				{
					title: 'Else',
					task: (ctx) => ctx.foo // Outputs foobar
				}
			], {}, {foo: ctx.baz});
		}
	}
]).run();

```

**Comment by SamVerschueren** [comment]
You should just be able to reference the outer `ctx` if you name it differently to avoid collisions.

```js
	{
		title: 'Something',
		task: (outerContext) => {
			return new Listr([
				{
					title: 'Else',
					task: (innerContext) => outerContext.baz
				}
			]);
		}
	}
```

**Comment by KristerV** [comment]
intrestingly if I separate outerTask and innerTask, then changing the `innerTask.title` results in the outer task title being changed.

**Comment by SamVerschueren** [comment]
That works perfectly for me though. Do you happen to have a small example showcasing the bug? Would help pinpointing it.

**Comment by KristerV** [comment]
ah, sorry I had mistaken two different problems. The one I mentioned is not actually a thing. I'll open another issue.

**Comment by SamVerschueren** [comment]
Closing this. Let me know if my answer is not enough.
